// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Load .env only in development (NOT in Render/production)
if (process.env.NODE_ENV !== "production") {
  await import("dotenv/config");
}

import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"), // Render will inject this
  },
});
